import {
    PhoneMissed,
    PhoneIncoming,
    PhoneOutgoing,
    Calendar,
    FileText,
    ClipboardCheck,
    Search,
    CheckCircle,
    AlarmClock,
    Bell,
    UserCheck,
    UserX,
    DollarSign,
    Banknote,
    ArrowLeftRight,
    FileCheck,
    FilePlus,
    Briefcase,
    Package,
    Timer,
    AlertTriangle,
} from "lucide-react";

export const TypeTask = [
    { name: "Follow-up", icon: <AlarmClock /> },
    { name: "Meeting", icon: <Calendar /> },
    { name: "Prelucrare", icon: <ClipboardCheck /> },
    { name: "Verificare", icon: <CheckCircle /> },
    { name: "Apel pierdut", icon: <PhoneMissed /> },
    { name: "Apel de intrare", icon: <PhoneIncoming /> },
    { name: "Reapel OFERTA", icon: <PhoneOutgoing /> },
    { name: "Apelare", icon: <PhoneOutgoing /> },
    { name: "Cautare TUR", icon: <Search /> },
    { name: "Ver. parteneri", icon: <UserCheck /> },
    { name: "Modificare contr", icon: <FileText /> },
    { name: "Rezervare", icon: <Briefcase /> },
    { name: "Contract", icon: <FileCheck /> },
    { name: "Verificare acte", icon: <FileCheck /> },
    { name: "Eliberare acte", icon: <FilePlus /> },
    { name: "Urgent", icon: <AlertTriangle /> },
    { name: "Check-in", icon: <Package /> },
    { name: "Chek-out", icon: <Package /> },
    { name: "CONTROL", icon: <ClipboardCheck /> },
    { name: "Cont. de plata", icon: <DollarSign /> },
    { name: "Achitare", icon: <Banknote /> },
    { name: "Ver. achitarii", icon: <CheckCircle /> },
    { name: "Retur banilor", icon: <ArrowLeftRight /> },
    { name: "New lead. Proc-g", icon: <UserX /> },
    { name: "Напомнить", icon: <Bell /> },
];  