export const TypeTask = [
    "Follow-up",
    "Meeting",
    "Prelucrare",
    "Verificare",
    "Apel pierdut",
    "Apel de intrare",
    "Reapel OFERTA",
    "Apelare",
    "Cautare TUR",
    "Ver. parteneri",
    "Modificare contr",
    "Rezervare",
    "Contract",
    "Verificare acte",
    "Eliberare acte",
    "Urgent",
    "Check-in",
    "Chek-out",
    "CONTROL",
    "Cont. de plata",
    "Achitare",
    "Ver. achitarii",
    "Retur banilor",
    "New lead. Proc-g",
    "Напомнить",
];