export const countryOptions = [
  "Albania",
  "Bulgaria",
  "Canada",
  "Cuba",
  "Cipru",
  "Dubai (Emiratele arabe unite)",
  "Grecia",
  "Grecia,Creta",
  "Egipt",
  "Israel",
  "Europa",
  "Franta",
  "India",
  "Indonesia,Balti",
  "Italia",
  "Maldive",
  "Moldova",
  "Muntenegru",
  "Romania",
  "Republica Dominicana",
  "Spania",
  "Sri Lanka",
  "Tanzania",
  "Tunisia",
  "Thailand",
  "Turcia",
  "Ucraina",
  "Ungaria",
  "USA",
  "Zanzibar",
  "Nu este specificat",
  "Altele"
];
