export const marketingOptions = [
  "Laponia",
  "Munte Alpi (Austria, Italia, Elvetia, Franta)",
  "Munte Bukovel",
  "Munte Bulgaria",
  "Munte Romania",
  "Croaziere",
  "Visa",
  "e-visa UAE",
  "e-visa Thailanda",
  "e-visa India",
  "e-visa Cuba",
  "e-visa Kenya",
  "e-visa Vietnam",
  "e-visa Iordania",
  "e-visa USA",
  "Excursii",
  "Excursii Moldova",
  "Excursii Romania",
  "Excursii Europa",
  "Excursii Budapesta",
  "Excursii pentru elevi",
  "Excursii pentru profesori",
  "Excursii corporative",
  "Pelerinaj",
  "Athotos",
  "Tratament",
  "Forum Dubai",
  "Tabara Iuliana Bereghoi 2025",
  "Targ de Creciun",
  "Bilete de avion",
  "Albania",
  "Excursie Istanbul",
  "Bali",
  "Bulgaria",
  "Dubai",
  "Egipt",
  "Cipru",
  "Grecia Avion",
  "Grecia Autocar",
  "India",
  "Maldive",
  "Mauritius",
  "R. Dominicana",
  "Spania",
  "Sri Lanka",
  "Thailanda",
  "Turcia",
  "Zanzibar",
  "Exotica",
  "Altele",
  "Nu e specificat"
]
