export const serviceTypeOptions = [
    "Sejur la Mare",
    "Excursii",
    "Pelerinaj",
    "Munte",
    "Croaziera",
    "Tratament",
    "CityBreak",
    "Angajare",
    "Bilete de avion",
    "Doar transport",
    "Green Card",
    "Viza",
    "Bilet de fotbal",
    "Tabara la munte cu Panda tur si Iuliana Beregoi",
    "Festival",
    "Recenzie",
    "Contact specialist",
    "Altele"
]